#!/bin/bash
TEMP_DIRECTORY=$(mktemp -d)
trap "{ rm -rf $TEMP_DIRECTORY; exit 255; }" EXIT SIGINT SIGTERM
cd $TEMP_DIRECTORY
wget https://github.com/cogneco/devtools/archive/master.zip
unzip -qj master.zip -d devtools && cd devtools
echo "Updating APT package lists (this may take a while)..."
sudo apt-get -qq update
./install_git
./install_nodejs
./install_vscode
./install_magic
./install_vslanguageooc

sudo cp install_vscode /usr/local/bin/update-vscode
