#!/bin/bash
TEMP_DIRECTORY=$(mktemp -d)
trap "{ rm -rf $TEMP_DIRECTORY; exit 255; }" EXIT SIGINT SIGTERM
cd $TEMP_DIRECTORY
wget https://github.com/magic-lang/magic-tools/archive/master.zip
unzip -qj master.zip -d magic-tools && cd magic-tools
echo "Updating APT package lists (this may take a while)..."
bash ./install_nodejs # this installer will update apt
bash ./install_devheaders
bash ./install_git
bash ./install_libav
bash ./install_valgrind
bash ./install_rock
bash ./install_magic
bash ./install_vscode
bash ./install_vslanguageooc
#
# Update scripts
#
bash ./install_magic-lang_updater
bash ./install_vscode_updater
