#!/bin/bash
TEMP_DIRECTORY=$(mktemp -d)
trap "{ rm -rf $TEMP_DIRECTORY; exit 255; }" EXIT SIGINT SIGTERM
cd $TEMP_DIRECTORY
wget https://github.com/cogneco/devtools/archive/master.zip
unzip -qj master.zip -d devtools && cd devtools
echo "Updating APT package lists (this may take a while)..."
bash ./install_nodejs # this installer will update apt
bash ./install_git
bash ./install_rock
bash ./install_magic
bash ./install_vscode
bash ./install_vslanguageooc
#
# Update scripts
#
bash ./install_ooc_updater
bash ./install_vscode_updater
